### ISSUE TITLE
Wireframe Creation

### ISSUE THREAD

**Issue by jenho-webdev** [jenho-webdev/MealMatch#2]
- wireframe drawing
- add to README

**Comment by Marinah1031** [comment]
- American
- Chinese
- Japanese
- Italian
- Mexican

**Comment by Homelesscats** [comment]
a mock-up open to changes.
suggest a change to having the selections exposed to fill up the page a bit.
![Image](https://github.com/jenho-webdev/MealMatch/assets/126728979/a0de3f2d-b561-4e13-919e-285badb678ba)

**Comment by jenho-webdev** [comment]
we will need to rest of the wireframe for how the app will work say after options is selected (or not) and after submit button was hit. an page for just the weekly meal plan view, a page for each meal's detail page? or some other page?

**Comment by Homelesscats** [comment]
five American dinner meals along with their approximate nutrition facts:

Grilled Chicken Breast with Steamed Vegetables and Brown Rice:
Grilled chicken breast (4 oz): 124 calories, 23g protein, 3g fat, 0g carbs
Steamed mixed vegetables (1 cup): 50 calories, 2g protein, 0g fat, 11g carbs
Brown rice (1/2 cup cooked): 108 calories, 2g protein, 1g fat, 22g carbs
Total: approximately 282 calories, 27g protein, 4g fat, 33g carbs

Spaghetti and Meatballs:
Whole wheat spaghetti (1 cup cooked): 174 calories, 7g protein, 1g fat, 37g carbs
Beef meatballs (3 oz): 219 calories, 18g protein, 15g fat, 2g carbs
Tomato sauce (1/2 cup): 54 calories, 2g protein, 1g fat, 10g carbs
Total: approximately 447 calories, 27g protein, 17g fat, 49g carbs

Grilled Salmon with Roasted Vegetables and Quinoa:
Grilled salmon (4 oz): 233 calories, 26g protein, 14g fat, 0g carbs
Roasted mixed vegetables (1 cup): 93 calories, 3g protein, 4g fat, 14g carbs
Quinoa (1/2 cup cooked): 111 calories, 4g protein, 2g fat, 20g carbs
Total: approximately 437 calories, 33g protein, 20g fat, 34g carbs

Beef Stir-Fry with Broccoli and Brown Rice:
Beef stir-fry (4 oz): 209 calories, 25g protein, 12g fat, 0g carbs
Broccoli (1 cup): 55 calories, 4g protein, 1g fat, 11g carbs
Brown rice (1/2 cup cooked): 108 calories, 2g protein, 1g fat, 22g carbs
Total: approximately 372 calories, 31g protein, 14g fat, 33g carbs

Veggie Burger with Sweet Potato Fries:
Veggie burger patty (1): 124 calories, 10g protein, 5g fat, 10g carbs
Whole wheat bun: 120 calories, 4g protein, 2g fat, 23g carbs
Sweet potato fries (1 cup): 114 calories, 1g protein, 5g fat, 18g carbs
Total: approximately 358 calories, 15g protein, 12g fat, 51g carbs
Note: These nutrition facts are approximate and may vary depending on the recipe and preparation methods used.

**Comment by Homelesscats** [comment]
Japanese food:

Teriyaki Salmon with Rice and Vegetables:
Calories: 500-600
Protein: 25-30 grams
Fat: 15-20 grams
Carbohydrates: 60-70 grams

Chicken Katsu Curry:
Calories: 700-800
Protein: 30-40 grams
Fat: 20-25 grams
Carbohydrates: 80-90 grams

Beef Bowl (Gyudon):
Calories: 600-700
Protein: 25-30 grams
Fat: 20-25 grams
Carbohydrates: 70-80 grams

Tofu and Vegetable Stir-Fry with Udon Noodles:
Calories: 400-500
Protein: 15-20 grams
Fat: 10-15 grams
Carbohydrates: 60-70 grams

Sushi Rolls with Miso Soup:
Calories: 300-400
Protein: 10-15 grams
Fat: 5-10 grams
Carbohydrates: 50-60 grams

**Comment by Homelesscats** [comment]
Italian:

Chicken Parmesan with Whole Wheat Spaghetti:
Chicken breast (4 oz): 124 calories, 23g protein, 3g fat, 0g carbs
Whole wheat spaghetti (1 cup cooked): 174 calories, 7g protein, 1g fat, 37g carbs
Tomato sauce (1/2 cup): 54 calories, 2g protein, 1g fat, 10g carbs
Mozzarella cheese (1 oz): 72 calories, 7g protein, 5g fat, 1g carbs
Total: approximately 424 calories, 39g protein, 10g fat, 48g carbs

Shrimp Scampi with Linguine:
Shrimp (4 oz): 112 calories, 23g protein, 1g fat, 1g carbs
Linguine (1 cup cooked): 221 calories, 8g protein, 1g fat, 43g carbs
Garlic, olive oil, lemon juice, and white wine sauce: (1/2 cup): 180 calories, 1g protein, 16g fat, 7g carbs
Total: approximately 513 calories, 32g protein, 18g fat, 51g carbs

Margherita Pizza:
Whole wheat pizza crust (1 slice): 135 calories, 5g protein, 1g fat, 28g carbs
Tomato sauce (1/4 cup): 27 calories, 1g protein, 0g fat, 6g carbs
Fresh mozzarella cheese (1 oz): 72 calories, 7g protein, 5g fat, 1g carbs
Fresh basil (2 leaves): 1 calorie, 0g protein, 0g fat, 0g carbs
Total: approximately 235 calories, 13g protein, 6g fat, 35g carbs

Minestrone Soup with Whole Wheat Bread:
Vegetable broth (1 cup): 15 calories, 0g protein, 0g fat, 3g carbs
Cannellini beans (1/2 cup): 110 calories, 8g protein, 0g fat, 20g carbs
Carrots, celery, zucchini, and tomatoes (1 cup): 70 calories, 2g protein, 0g fat, 16g carbs
Whole wheat bread (1 slice): 100 calories, 5g protein, 1g fat, 20g carbs
Total: approximately 295 calories, 15g protein, 1g fat, 59g carbs

Eggplant Parmesan with Mixed Greens Salad:
Eggplant (1/2 cup): 14 calories, 1g protein, 0g fat, 3g carbs
Whole wheat breadcrumbs (1/4 cup): 56 calories, 2g protein, 0g fat, 12g carbs
Tomato sauce (1/2 cup): 54 calories, 2g protein, 1g fat, 10g carbs
Mozzarella cheese (1 oz): 72 calories, 7g protein, 5g fat, 1g carbs
Mixed greens salad with balsamic vinaigrette (2 cups): 70 calories, 2g protein, 5g fat, 6g carbs
Total: approximately 266 calories, 14g protein, 11g fat, 32g carbs

**Comment by Homelesscats** [comment]
Chinese Inspired Food:

Kung Pao Chicken with Brown Rice:
Chicken breast (4 oz): 124 calories, 23g protein, 3g fat, 0g carbs
Brown rice (1 cup cooked): 218 calories, 5g protein, 2g fat, 46g carbs
Mixed vegetables (1 cup): 50 calories, 2g protein, 0g fat, 12g carbs
Kung Pao sauce (1/4 cup): 100 calories, 0g protein, 9g fat, 5g carbs
Total: approximately 492 calories, 30g protein, 14g fat, 63g carbs

Beef and Broccoli Stir-Fry with Quinoa:
Beef sirloin (4 oz): 172 calories, 22g protein, 8g fat, 0g carbs
Broccoli (1 cup): 55 calories, 4g protein, 1g fat, 11g carbs
Quinoa (1 cup cooked): 222 calories, 8g protein, 4g fat, 39g carbs
Stir-fry sauce (1/4 cup): 60 calories, 1g protein, 0g fat, 15g carbs
Total: approximately 509 calories, 35g protein, 13g fat, 65g carbs

Hot and Sour Soup with Vegetable Spring Rolls:
Hot and sour soup (1 cup): 110 calories, 4g protein, 2g fat, 19g carbs
Vegetable spring rolls (2 pieces): 180 calories, 5g protein, 7g fat, 26g carbs
Total: approximately 290 calories, 9g protein, 9g fat, 45g carbs

Shrimp Lo Mein:
Shrimp (4 oz): 112 calories, 23g protein, 1g fat, 1g carbs
Lo mein noodles (1 cup cooked): 237 calories, 8g protein, 2g fat, 46g carbs
Mixed vegetables (1 cup): 50 calories, 2g protein, 0g fat, 12g carbs
Stir-fry sauce (1/4 cup): 60 calories, 1g protein, 0g fat, 15g carbs
Total: approximately 459 calories, 34g protein, 3g fat, 74g carbs

Moo Shu Pork with Steamed Rice:
Pork tenderloin (4 oz): 120 calories, 23g protein, 3g fat, 0g carbs
Steamed white rice (1 cup): 169 calories, 3g protein, 0g fat, 37g carbs
Moo shu sauce (1/4 cup): 70 calories, 0g protein, 5g fat, 6g carbs
Mixed vegetables (1 cup): 50 calories, 2g protein, 0g fat, 12g carbs
Moo shu pancakes (2): 100 calories, 3g protein, 1g fat, 20g carbs
Total: approximately 509 calories, 31g protein, 9g fat, 75g carbs

**Comment by Homelesscats** [comment]
Chicken Fajitas with Brown Rice and Black Beans:
Chicken breast (4 oz): 124 calories, 23g protein, 3g fat, 0g carbs
Bell peppers and onions (1 cup): 50 calories, 1g protein, 0g fat, 12g carbs
Brown rice (1 cup cooked): 218 calories, 5g protein, 2g fat, 46g carbs
Black beans (1/2 cup): 110 calories, 8g protein, 0g fat, 20g carbs
Fajita seasoning (1 tbsp): 15 calories, 0g protein, 0g fat, 3g carbs
Flour tortilla (1 medium): 120 calories, 3g protein, 3g fat, 20g carbs
Total: approximately 637 calories, 40g protein, 8g fat, 101g carbs

Shrimp Tacos with Cilantro Lime Rice:
Shrimp (4 oz): 112 calories, 23g protein, 1g fat, 1g carbs
Corn tortillas (2): 100 calories, 2g protein, 2g fat, 20g carbs
Cabbage slaw (1 cup): 35 calories, 1g protein, 0g fat, 8g carbs
Avocado (1/2): 117 calories, 1g protein, 11g fat, 6g carbs
Cilantro lime rice (1 cup cooked): 190 calories, 4g protein, 3g fat, 37g carbs
Total: approximately 554 calories, 31g protein, 17g fat, 92g carbs

Beef Enchiladas with Refried Beans:
Ground beef (4 oz): 233 calories, 19g protein, 17g fat, 0g carbs
Corn tortillas (2): 100 calories, 2g protein, 2g fat, 20g carbs
Enchilada sauce (1/2 cup): 100 calories, 2g protein, 4g fat, 16g carbs
Cheddar cheese (1/4 cup shredded): 114 calories, 7g protein, 9g fat, 1g carbs
Refried beans (1/2 cup): 120 calories, 6g protein, 3g fat, 17g carbs
Total: approximately 667 calories, 36g protein, 35g fat, 74g carbs

Steak and Veggie Burrito Bowl:
Steak (4 oz): 156 calories, 25g protein, 5g fat, 0g carbs
Brown rice (1 cup cooked): 218 calories, 5g protein, 2g fat, 46g carbs
Mixed vegetables (1 cup): 50 calories, 2g protein, 0g fat, 12g carbs
Guacamole (2 tbsp): 50 calories, 1g protein, 5g fat, 2g carbs
Salsa (2 tbsp): 10 calories, 0g protein, 0g fat, 2g carbs
Total: approximately 484 calories, 33g protein, 12g fat, 62g carbs

Chicken Tortilla Soup with Salad:
Chicken breast (4 oz): 124 calories, 23g protein, 3g fat, 0g carbs
Tortilla strips (1/2 cup)

**Comment by Homelesscats** [comment]
exercise: 
-WALKING
The number of calories burned while walking depends on several factors, such as your weight, the distance walked, and the speed at which you walk. On average, a person who weighs 150 pounds (68 kg) will burn approximately 100-125 calories per mile (1.6 km) walked at a moderate pace (3-4 mph or 4.8-6.4 kph).

So, if you were to walk for an hour at a moderate pace, you could expect to burn between 300 and 500 calories, depending on your weight and other factors. However, it's important to keep in mind that this is just an estimate and individual results may vary.

Running:

The number of calories burned while running depends on several factors, such as your weight, the distance run, and the intensity of your run. On average, a person who weighs 150 pounds (68 kg) will burn approximately 100 calories per mile (1.6 km) run, regardless of speed.

So, if you were to run for an hour at a moderate pace (about 5 mph or 8 kph), you could expect to cover approximately 5 miles (8 km) and burn around 500 calories. However, if you were to run at a faster pace or run uphill, you could burn more calories per hour.

It's important to keep in mind that these are just estimates and individual results may vary based on factors such as age, gender, body composition, and overall fitness level.

Cycling:


The number of calories burned while bicycling depends on several factors, such as your weight, the distance biked, the speed, and the terrain. On average, a person who weighs 150 pounds (68 kg) will burn approximately 240-290 calories per hour of bicycling at a moderate pace (about 12-14 mph or 19-22.5 kph).

However, the number of calories burned can vary greatly depending on the factors mentioned above. For example, cycling at a faster pace or uphill will burn more calories, while cycling at a leisurely pace or downhill will burn fewer calories.

It's important to keep in mind that these are just estimates and individual results may vary based on factors such as age, gender, body composition, and overall fitness level.


Swimming:

The number of calories burned while swimming depends on several factors, such as your weight, the intensity of your swim, and the stroke used. On average, a person who weighs 150 pounds (68 kg) can burn approximately 400-500 calories per hour of swimming laps at a moderate pace.

However, the number of calories burned can vary greatly depending on the factors mentioned above. For example, a person may burn more calories per hour while doing a more intense swim, such as freestyle sprints or butterfly strokes, compared to a more leisurely swim at a slower pace.

It's also important to note that swimming in colder water can cause the body to burn more calories to maintain body temperature, compared to swimming in warmer water.

It's important to keep in mind that these are just estimates and individual results may vary based on factors such as age, gender, body composition, and overall fitness level.

Boxing/Kickboxing:

The number of calories burned during boxing/kickboxing depends on several factors, such as your weight, intensity level, and duration of the workout. On average, a person who weighs 150 pounds (68 kg) can burn approximately 400-700 calories per hour of boxing/kickboxing.

However, the number of calories burned can vary greatly depending on the factors mentioned above. For example, a high-intensity kickboxing workout that involves a lot of kicking and punching can burn more calories than a more relaxed boxing workout that involves more shadowboxing and technique work.

It's important to keep in mind that these are just estimates and individual results may vary based on factors such as age, gender, body composition, and overall fitness level. Additionally, boxing/kickboxing can be a high-impact activity that may not be suitable for everyone, especially those with joint issues or injuries.



Source: CHAT GPT

**Comment by Homelesscats** [comment]
"we will need to rest of the wireframe for how the app will work say after options is selected (or not) and after submit button was hit. an page for just the weekly meal plan view, a page for each meal's detail page? or some other page?"

So for now I will be putting each one of these on a card

**Comment by jenho-webdev** [comment]
After all the conversations, below is what a MVP looks like:

- 3 html pages

1. >index.html
3. >recripeDetails.html 


![Image](https://github.com/jenho-webdev/MealMatch/assets/129031553/49aa9609-220f-489d-98ec-81c3ef4f0d3b)

-For the main page:
>Form:
>one drop option for cuisines
>>American
>>Chinese
>>Japanese
>>talian
>>Mexican

>A "search" button
>>Nav Bar consist of:
>>Home button that link to home page
>>recipes book (AKA user's saved recipes)

-searchResult Div that contain two containers that is side by side



 and 3 buttons

>Recipe Container 
>>img of the recipe
>>Title of the recipe
>>Ready in (mins)
>>isVegan?: YES or NO
>>Calories:  INT ( in bold text)
>>RecipID: a number that is hidden

>Sport Container
>>sport cards for each type of sport
>>> Card header = sport name
>>>card body = sport data
>>>>calories burn rate(per hour)
>>>>result: duration needed to do the sport to burn out the returned recipe
>>>>URL to the sport in detail? 

>Buttons
>>Save recipe to recipes book
>>Search again > redirect to home page



> name

**Comment by jenho-webdev** [comment]
Recipe Page: 



![Image](https://github.com/jenho-webdev/MealMatch/assets/129031553/2a2ef9e1-35bf-4170-bedf-8155a00bbe2c)

-Header: same as main page with logo and nav bar
-body contain 
>recipeDetail container
>>left col 
>>>recipe img box
>>>sport detail container
>>Right Col
>>>Recipe Title
>>> horizontal line
>>>container for recipe ingredients
>>>container for recipe cooking direction
>>save button a bottom

**Comment by jenho-webdev** [comment]
where and how we want to do the saved recipes?
