### ISSUE TITLE
Linking API (atleast 2)

### ISSUE THREAD

**Issue by Marinah1031** [jenho-webdev/MealMatch#3]
Using the websites:
https://api-ninjas.com/api/caloriesburned 
https://spoonacular.com/food-api

**Comment by Marinah1031** [comment]
API KEY = qeQ/ixgJ1FhLzMigxs+yag==sahHalNRb0bq0szN

**Comment by jenho-webdev** [comment]
Spoonacular API :

Parameters: Cuisine
Type: String
List of supported cuisines: Chinese, Japanese, American, Italian, Mexican
[API Doc](https://spoonacular.com/food-api/docs#Cuisines)

Parameters: diet
type: String
Values: Vegan,Keto,Gluten-Free
[API Doc](https://spoonacular.com/food-api/docs#Diets)
