### ISSUE TITLE
Change the Tag line with a more fun msg

### ISSUE THREAD

**Issue by jenho-webdev** [jenho-webdev/MealMatch#52]
Refinemenet: 

would like to request the search box text to something like the below.

"Find Your Recipe Match and Burn It Off!"
"Discover Deliciousness, Burn the Calories!"
"Cuisine Search: Recipes and Calorie Burn Companion"
"Taste the Flavors, Sweat the Calories"
"Search, Savor, Sweat: Find Your Fitness Recipe"
"Unleash Your Inner Chef, Fuel Your Active Lifestyle"
"Recipe Roulette: Find Flavors, Burn Calories!"
"From Plate to Pace: Discover, Devour, and Shed"
"Calorie Search: Flavorful Recipes, Active Results"
"Eat Well, Move More: Discover, Devour, Burn!"
"Search, Cook, Sweat: Uncover the Perfect Pairing"

**Comment by Homelesscats** [comment]
Ill do this and create the pr
