### ISSUE TITLE
Create acceptance criteria

### ISSUE THREAD

**Issue by meekunn1** [jenho-webdev/MealMatch#6]

**Comment by Marinah1031** [comment]
- Choose from a list of cuisines in a dropdown list. (5) 
- Choose from a list of activities in a dropdown list. (bike, run, walk)
- When the user selects a cuisine and activity, then a recipe with the duration of work out will be displayed that correlates the calories in and out. 
- User is able to bookmark a recipe bank with the workout duration.
-  At least 2 API used)
- Use Material UI (MUI)
- Be responsive (CSS) REM no pixels 
- *if it cannot call, must be responsive (front and backend)
- README file
